/**
 * AI Onboarding Import — accepts a JSON brief generated by an external
 * LLM (Claude / ChatGPT via the SHOMEE skill), resolves its localisation
 * query to IRIS zones, and seeds the Zustand store so the user lands on
 * a pre-filled recap screen.
 *
 * Flow:
 *   1. Parse + validate JSON with Zod
 *   2. POST /api/location/analyze  → LocationIntentAnalysis
 *   3. Load geo data in parallel (arrondissements / quartiers / communes / iris)
 *   4. resolveConstraints(...) → IRIS ids
 *   5. derive parent arr / quartier / commune from selected IRIS
 *   6. useSearchStore.setState({...})  +  addCustomCriteria(brief.customCriteria)
 *
 * On geo-resolution failure: the store is still seeded with `locationQuery`
 * + the rest of the brief; `selectedIrisIds` stays empty so the user can
 * fix the localisation later from the recap.
 */

import { z } from 'zod'
import { useSearchStore, type ChipState } from '@/lib/searchStore'
import {
  fetchParisArrondissements,
  fetchParisQuartiers,
  fetchParisIris,
  fetchSuburbanCommunes,
  type GeoZone,
} from './geoDataService'
import { resolveConstraints, type GeoConstraint } from './geoConstraintService'
import type { LocationIntentAnalysis } from './locationIntentAnalyzerService'

// ─── Zod schema ────────────────────────────────────────────────────────────

const ChipStateSchema = z.union([z.literal(1), z.literal(2), z.literal(3)])

export const AIOnboardingBriefSchema = z.object({
  // Required
  locationQuery: z.string().min(1, 'locationQuery vide'),
  minSurface: z.number().nullable(),
  budgetMax: z.number().nullable(),

  // Optional with defaults
  propertyTypes: z
    .array(z.enum(['appartement', 'maison', 'loft', 'atelier']))
    .optional()
    .default([]),
  minRooms: z.number().nullable().optional().default(null),
  maxSurface: z.number().nullable().optional().default(null),
  budgetMin: z.number().nullable().optional().default(null),
  chipStates: z.record(z.string(), ChipStateSchema).optional().default({}),
  customCriteria: z
    .array(
      z.object({
        label: z.string().min(1),
        state: ChipStateSchema,
        polarity: z.enum(['positive', 'negative']).optional(),
      }),
    )
    .optional()
    .default([]),
})

export type AIOnboardingBrief = z.infer<typeof AIOnboardingBriefSchema>

// ─── Result types ──────────────────────────────────────────────────────────

export interface ImportSuccess {
  success: true
  /** Human-readable summary the recap can display (e.g. "Paris 12 · Aligre"). */
  locationLabel: string
  irisCount: number
  /** True when /api/location/analyze succeeded AND irisCount > 0. False when
   *  the store was seeded without IRIS resolution. */
  geoResolved: boolean
}

export interface ImportFailure {
  success: false
  /** Human-readable French error to surface in the drawer. */
  error: string
}

export type ImportResult = ImportSuccess | ImportFailure

// ─── Error messages ────────────────────────────────────────────────────────

const FIELD_ERRORS: Record<string, string> = {
  locationQuery: 'Il manque la zone de recherche (champ "locationQuery").',
  minSurface: 'Il manque la surface minimum (champ "minSurface").',
  budgetMax: 'Il manque le budget maximum (champ "budgetMax").',
}

function zodErrorToFrench(err: z.ZodError): string {
  const issue = err.issues[0]
  if (!issue) return 'Brief invalide.'
  const fieldPath = issue.path.join('.')
  const fieldMsg = FIELD_ERRORS[fieldPath]
  if (fieldMsg) return fieldMsg
  if (issue.code === 'invalid_type' && (issue as { received?: unknown }).received === 'undefined') {
    return `Champ requis manquant : "${fieldPath}".`
  }
  return `Champ "${fieldPath}" invalide : ${issue.message}`
}

// ─── Public API ────────────────────────────────────────────────────────────

export async function importAIBrief(raw: string): Promise<ImportResult> {
  // 1. Parse JSON
  let parsedJson: unknown
  try {
    parsedJson = JSON.parse(raw.trim())
  } catch {
    return {
      success: false,
      error:
        'Le format ne semble pas correct. Vérifiez que vous avez copié le brief complet (JSON entre accolades).',
    }
  }

  // 2. Zod validation
  const validation = AIOnboardingBriefSchema.safeParse(parsedJson)
  if (!validation.success) {
    return { success: false, error: zodErrorToFrench(validation.error) }
  }
  const brief = validation.data

  // 3. Analyze location → 4. resolve constraints
  let analysis: LocationIntentAnalysis | null = null
  let irisIds: string[] = []
  let arrIds: string[] = []
  let quartierIds: string[] = []
  let communeIds: string[] = []
  let locationLabel = brief.locationQuery
  let geoResolved = false

  try {
    const res = await fetch('/api/location/analyze', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ input: brief.locationQuery }),
    })
    if (res.ok) analysis = (await res.json()) as LocationIntentAnalysis
  } catch {
    // network error — leave analysis null
  }

  if (analysis) {
    const constraints: GeoConstraint[] = analysis.geoConstraints ?? []
    if (constraints.length > 0) {
      try {
        const [arrs, qus, communes] = await Promise.all([
          fetchParisArrondissements(),
          fetchParisQuartiers(),
          fetchSuburbanCommunes(),
        ])
        const iris = await fetchParisIris(qus, communes)
        const result = resolveConstraints(constraints, iris, qus, communes)
        irisIds = result.irisIds
        ;({ arrIds, quartierIds, communeIds } = deriveParents(irisIds, iris, qus))
        if (result.matchSummary.length > 0) {
          locationLabel = result.matchSummary.join(' · ')
        } else if (analysis.mapAction?.centerQuery) {
          locationLabel = analysis.mapAction.centerQuery
        }
        // Silence the unused arr binding when we don't need it for derivation
        void arrs
        geoResolved = irisIds.length > 0
      } catch (e) {
        console.warn('[aiImport] geo resolution failed:', e)
      }
    } else if (analysis.mapAction?.centerQuery) {
      locationLabel = analysis.mapAction.centerQuery
    }
  }

  // 5. Seed store atomically (location + numeric fields + chipStates)
  useSearchStore.setState({
    locationQuery: brief.locationQuery,
    locationLabel,
    locationLat: null,
    locationLng: null,
    locationIntent: analysis
      ? {
          location_terms: analysis.explicitLocations?.map((l) => l.label) ?? [],
          lifestyle_terms: [],
          transport_constraints: [],
          confidence: 1,
          geoConstraints: analysis.geoConstraints,
          resolutionStrategy: analysis.resolutionStrategy,
        }
      : null,
    selectedArrIds: arrIds,
    selectedQuartierIds: quartierIds,
    selectedIrisIds: irisIds,
    selectedCommuneIds: communeIds,
    propertyTypes: brief.propertyTypes,
    minRooms: brief.minRooms,
    minSurface: brief.minSurface,
    maxSurface: brief.maxSurface,
    budgetMin: brief.budgetMin,
    budgetMax: brief.budgetMax,
    chipStates: brief.chipStates as Record<string, ChipState>,
    // Reset any previous custom criteria — the brief is authoritative.
    customCriteria: [],
  })

  // 6. Inject custom criteria via the store action (handles id generation +
  //    polarity defaults). State is preserved exactly as provided by the brief.
  if (brief.customCriteria.length > 0) {
    useSearchStore.getState().addCustomCriteria(
      brief.customCriteria.map((c) => ({
        label: c.label,
        state: c.state as ChipState,
        polarity: c.polarity,
      })),
    )
  }

  return { success: true, locationLabel, irisCount: irisIds.length, geoResolved }
}

// ─── Helpers ───────────────────────────────────────────────────────────────

function deriveParents(
  irisIds: string[],
  iris: GeoZone[],
  quartiers: GeoZone[],
): { arrIds: string[]; quartierIds: string[]; communeIds: string[] } {
  const irisById = new Map(iris.map((i) => [i.id, i]))
  const quartierById = new Map(quartiers.map((q) => [q.id, q]))
  const arrIds = new Set<string>()
  const quartierIds = new Set<string>()
  const communeIds = new Set<string>()
  for (const id of irisIds) {
    const z = irisById.get(id)
    if (!z?.parentId) continue
    if (z.parentId.startsWith('qu-')) {
      quartierIds.add(z.parentId)
      const q = quartierById.get(z.parentId)
      if (q?.parentId) arrIds.add(q.parentId)
    } else if (z.parentId.startsWith('arr-')) {
      arrIds.add(z.parentId)
    } else if (z.parentId.startsWith('com-')) {
      communeIds.add(z.parentId)
    }
  }
  return {
    arrIds: [...arrIds],
    quartierIds: [...quartierIds],
    communeIds: [...communeIds],
  }
}
