/**
 * Shomee — web type surface.
 *
 * View-model types (`Property`, `ChatMessage`, `Conversation`) now live in
 * `@shomee/core` (single source of truth, shared web + mobile) and are
 * re-exported here so existing `@/lib/types` imports keep working unchanged.
 *
 * Persistence-level entity types (User, Agent, Agency, BuyerProfile,
 * PropertyTag, VideoAnalysis, Document) and enums are generated by Prisma
 * and re-exported below — they are server-only and intentionally NOT part
 * of `@shomee/core`.
 */

import type {
  User,
  Agent,
  Agency,
  BuyerProfile,
  PropertyTag,
  VideoAnalysis,
  Document,
  Property as PrismaProperty,
  UserRole,
  AgencyPlan,
  MandatType,
  PropertyStatus,
  TagSource,
  VideoAnalysisStatus,
  DocumentType,
  PropertyBadge,
  DpeRating,
} from '@prisma/client'

export type {
  User,
  Agent,
  Agency,
  BuyerProfile,
  PropertyTag,
  VideoAnalysis,
  Document,
  PrismaProperty,
  UserRole,
  AgencyPlan,
  MandatType,
  PropertyStatus,
  TagSource,
  VideoAnalysisStatus,
  DocumentType,
  PropertyBadge,
  DpeRating,
}

// View-model types — single source of truth in @shomee/core.
export type { Property, ChatMessage, Conversation } from '@shomee/core/types/domain'
