/**
 * Shomee — criteria parsing types.
 *
 * Domain model for the user-criteria engine. These types describe what
 * a parsed criterion looks like after the LLM has turned a free-text
 * description ("terrasse d'au moins 15 m²") into a structured rule.
 *
 * The parser produces `ParsedCriterion[]`; the API route wraps that in
 * a `UserCriteriaBrief` along with the original raw tags and text.
 */

export type CriterionImportance = 'desired' | 'mandatory' | 'dealbreaker'

export type CriterionMatchType =
  | 'structured_rule'   // calculable: surface ≥ 15, exposition = sud, …
  | 'conditional_rule'  // si X alors Y (étage ≥ 3 → ascenseur = true)
  | 'semantic'          // qualitatif: lumineux, calme, traversant
  | 'fuzzy'             // émotionnel: cocon, charme, cachet

export type CriterionCategory =
  | 'outdoor'
  | 'bedroom'
  | 'living'
  | 'building'
  | 'location'
  | 'ambiance'

export type CriterionPolarity = 'positive' | 'negative'

/**
 * Operators supported by structured rules. String, number and boolean
 * comparisons all flow through the same shape; downstream matchers
 * dispatch based on the value type.
 */
export type RuleOperator = '=' | '!=' | '>' | '>=' | '<' | '<=' | 'in' | 'not_in'

export type RuleValue = string | number | boolean | Array<string | number>

export interface StructuredRule {
  attribute: string
  operator: RuleOperator
  value: RuleValue
}

export interface ConditionalRule {
  if: StructuredRule
  then: StructuredRule
}

export type Rule = StructuredRule | ConditionalRule

export interface ParsedCriterion {
  /** Stable identifier, UUID v4. Generated by the parser. */
  id: string
  /** Human-readable reformulation, shown in the UI. */
  display_label: string
  category: CriterionCategory
  polarity: CriterionPolarity
  importance: CriterionImportance
  match_type: CriterionMatchType
  /** Structured rule when `match_type` is `structured_rule` /
   *  `conditional_rule`; `null` otherwise. */
  rule: Rule | null
  /** Free-form hint used by semantic/fuzzy matchers; `null` for rule-based. */
  semantic_hint: string | null
  /** Original phrase from the user, kept verbatim for traceability. */
  raw_input: string
  /** Parser confidence, 0–1. */
  confidence: number
  /** True when the user has manually overridden the inferred importance
   *  (so the engine knows to preserve their choice on re-parse). */
  importance_override: boolean
}

export interface UserCriteriaBrief {
  user_id: string
  parsed_criteria: ParsedCriterion[]
  /** The list of predefined tags the user clicked on. */
  raw_tags: string[]
  /** The free-text input fed to the parser. */
  raw_text_input: string
  /** ISO-8601 timestamps. */
  created_at: string
  updated_at: string
}

// ─── Type guards ────────────────────────────────────────────────────────────

export function isStructuredRule(rule: Rule | null | undefined): rule is StructuredRule {
  return !!rule && 'attribute' in rule && 'operator' in rule && 'value' in rule
}

export function isConditionalRule(rule: Rule | null | undefined): rule is ConditionalRule {
  return !!rule && 'if' in rule && 'then' in rule
}
