import type { Property } from './types'

export const properties: Property[] = [
  {
    id: '1',
    arrondissement: 'PARIS 18e',
    subtitle: 'Penthouse en duplex',
    agentName: 'Agence Junot',
    title: 'Penthouse duplex Montmartre',
    price: 1490000,
    pricePerSqm: 12957,
    surface: 115,
    rooms: 5,
    bedrooms: 3,
    location: 'Paris 75018',
    district: 'Montmartre',
    description:
      "Exceptionnel penthouse en duplex au sommet d'un immeuble de caractère à Montmartre. Vue panoramique sur Paris, terrasse privative de 28m², double séjour avec verrière. Finitions haut de gamme, parquet massif, cuisine ouverte équipée. Rare sur le marché.",
    tags: ['Extérieur', 'Lumineux', 'Charme ancien'],
    features: ['Terrasse', 'Vue panoramique', 'Duplex', 'Cave', 'Ascenseur'],
    dpe: 'C',
    ges: 'C',
    floor: 6,
    totalFloors: 6,
    orientation: 'Sud-Ouest',
    exteriorType: 'Terrasse 28m²',
    heatingType: 'Individuel (électrique)',
    hotWaterType: 'Individuel (électrique)',
    yearBuilt: 1910,
    lotCount: 12,
    proceduresEnCours: false,
    monthlyCharges: 420,
    propertyTax: 2100,
    composition: [
      { label: 'Séjour / salle à manger', surface: 42 },
      { label: 'Cuisine ouverte', surface: 14 },
      { label: 'Terrasse', surface: 28 },
      { label: 'Chambre parentale', surface: 18 },
      { label: 'Chambre 2', surface: 12 },
      { label: 'Chambre 3', surface: 11 },
      { label: 'Salle de bain', surface: 8 },
      { label: 'Salle d\'eau', surface: 5 },
      { label: 'Entrée / dégagement', surface: 5 },
    ],
    irisZone: 'Abbesses – Grandes Carrières',
    irisDescription: 'Micro-quartier animé au cœur de la Butte Montmartre, entre la Place des Abbesses et le Sacré-Cœur.',
    mapLat: 48.8871,
    mapLng: 2.3436,
    transports: ['M12 Abbesses', 'M2 Pigalle', 'Bus 80'],
    nearbyPlaces: ['Place des Abbesses', 'Sacré-Cœur', 'Rue Lepic'],
    neighborhoodVibe: 'Artistique & villageois',
    marketAvgPricePerSqm: 11800,
    marketEvolution10y: '+31%',
    marketHighPrice: 15200,
    marketLowPrice: 9400,
    videoUrl: '/videos/bien-1.mp4',
    imageUrlFallback:
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=1400&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&h=600&fit=crop&q=80',
    ],
    chapters: [
      { label: 'Entrée',        fraction: 0    },
      { label: 'Terrasse',      fraction: 0.12 },
      { label: 'Salon',         fraction: 0.20 },
      { label: 'Chambre',       fraction: 0.32 },
      { label: 'Salle de bain', fraction: 0.48 },
      { label: 'Entrée',        fraction: 0.52 },
      { label: 'Salon',         fraction: 0.64 },
      { label: 'Terrasse',      fraction: 0.76 },
      { label: 'Salon',         fraction: 0.84 },
    ],
    likeCount: 312,
    shareCount: 94,
    promising: false,
  },
  {
    id: '2',
    arrondissement: 'PARIS 4e',
    subtitle: 'T2 Île Saint-Louis',
    agentName: 'Agence Frédélion',
    title: 'T2 Île Saint-Louis',
    price: 580000,
    pricePerSqm: 15263,
    surface: 38,
    rooms: 2,
    bedrooms: 1,
    location: 'Paris 75004',
    district: 'Île Saint-Louis',
    description:
      "Charmant T2 au cœur de l'Île Saint-Louis, l'un des quartiers les plus prisés de Paris. Pierres apparentes, poutres d'époque, vue sur cour arborée. Cuisine rénovée, salle de bain refaite à neuf. Idéal résidence principale ou investissement locatif premium.",
    tags: ['Charme ancien', 'Calme', 'Lumineux'],
    features: ['Pierres apparentes', 'Poutres', 'Cour', 'Cave'],
    dpe: 'D',
    ges: 'D',
    floor: 3,
    totalFloors: 5,
    orientation: 'Est',
    exteriorType: 'Cour intérieure',
    heatingType: 'Collectif (gaz)',
    hotWaterType: 'Collectif (gaz)',
    yearBuilt: 1640,
    lotCount: 8,
    proceduresEnCours: false,
    monthlyCharges: 280,
    propertyTax: 1350,
    composition: [
      { label: 'Séjour', surface: 18 },
      { label: 'Cuisine', surface: 6 },
      { label: 'Chambre', surface: 10 },
      { label: 'Salle de bain', surface: 4 },
    ],
    irisZone: 'Île Saint-Louis – Cité',
    irisDescription: 'L\'une des îles les plus exclusives de Paris, architecture du XVIIe siècle, calme et vue sur Seine.',
    mapLat: 48.8520,
    mapLng: 2.3560,
    transports: ['M7 Pont Marie', 'M1 Saint-Paul', 'Bus 67'],
    nearbyPlaces: ['Notre-Dame de Paris', 'Marché Saint-Germain', 'Pont de la Tournelle'],
    neighborhoodVibe: 'Exclusif & historique',
    marketAvgPricePerSqm: 14800,
    marketEvolution10y: '+22%',
    marketHighPrice: 19500,
    marketLowPrice: 11200,
    videoUrl: '/videos/bien-2.mp4',
    imageUrlFallback:
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=1400&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop&q=80',
    ],
    chapters: [
      { label: 'Salle à manger', fraction: 0    },
      { label: 'Salon',          fraction: 0.41 },
      { label: 'Chambre',        fraction: 0.83 },
    ],
    likeCount: 187,
    shareCount: 52,
    promising: true,
  },
  {
    id: '3',
    arrondissement: 'PARIS 6e',
    subtitle: 'T4 Saint-Germain-des-Prés',
    agentName: 'Kretz Real Estate',
    title: 'T4 Saint-Germain-des-Prés',
    price: 2350000,
    pricePerSqm: 25824,
    surface: 91,
    rooms: 4,
    bedrooms: 2,
    location: 'Paris 75006',
    district: 'Saint-Germain-des-Prés',
    description:
      "Somptueux T4 dans un hôtel particulier du XVIIe siècle au cœur de Saint-Germain-des-Prés. Grand séjour traversant avec moulures d'époque, deux chambres en suite, cuisine équipée haut de gamme. Cachet exceptionnel, prestations luxe. Gardien en loge.",
    tags: ['Charme ancien', 'Calme', 'Lumineux'],
    features: ['Hôtel particulier', 'Moulures', 'Gardien', 'Cave', 'Ascenseur'],
    dpe: 'B',
    ges: 'B',
    floor: 2,
    totalFloors: 4,
    orientation: 'Sud traversant',
    exteriorType: 'Balcon',
    heatingType: 'Individuel (gaz)',
    hotWaterType: 'Individuel (gaz)',
    yearBuilt: 1680,
    lotCount: 6,
    proceduresEnCours: false,
    monthlyCharges: 680,
    propertyTax: 4200,
    composition: [
      { label: 'Séjour / salle à manger', surface: 38 },
      { label: 'Cuisine équipée', surface: 14 },
      { label: 'Chambre parentale', surface: 20 },
      { label: 'Chambre 2', surface: 14 },
      { label: 'Salle de bain', surface: 8 },
      { label: 'Entrée', surface: 7 },
    ],
    irisZone: 'Odéon – Saint-Germain',
    irisDescription: 'Le quartier le plus prisé de la Rive Gauche, entre galeries d\'art, librairies et restaurants étoilés.',
    mapLat: 48.8540,
    mapLng: 2.3332,
    transports: ['M4 Saint-Germain-des-Prés', 'M10 Mabillon', 'Bus 39'],
    nearbyPlaces: ['Jardin du Luxembourg', 'Église Saint-Germain', 'Rue de Buci'],
    neighborhoodVibe: 'Intellectuel & gastronomique',
    marketAvgPricePerSqm: 23500,
    marketEvolution10y: '+18%',
    marketHighPrice: 31000,
    marketLowPrice: 18000,
    videoUrl: '/videos/bien-3.mp4',
    imageUrlFallback:
      'https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=800&h=1400&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=800&h=600&fit=crop&q=80',
      'https://images.unsplash.com/photo-1630699144867-37acec97df5a?w=800&h=600&fit=crop&q=80',
      'https://images.unsplash.com/photo-1617104551722-3b2d51bfb183?w=800&h=600&fit=crop&q=80',
    ],
    chapters: [
      { label: 'Quartier',          fraction: 0    },
      { label: 'Séjour',            fraction: 0.15 },
      { label: 'Cuisine',           fraction: 0.47 },
      { label: 'Chambre parentale', fraction: 0.66 },
      { label: 'Chambre enfant',    fraction: 0.72 },
      { label: 'Séjour',            fraction: 0.80 },
    ],
    likeCount: 326,
    shareCount: 164,
    promising: false,
  },
  {
    id: '4',
    arrondissement: 'PARIS 12e',
    subtitle: 'T3 Aligre',
    agentName: 'Agence Abriculteurs',
    title: 'T3 Paris 12e — Aligre',
    price: 500000,
    pricePerSqm: 10638,
    surface: 47,
    rooms: 3,
    bedrooms: 2,
    location: 'Paris 75012',
    district: 'Aligre',
    description:
      "Beau T3 traversant au cœur du 12e, à deux pas du marché d'Aligre. Séjour lumineux, cuisine équipée ouverte sur le séjour, deux chambres dont une avec dressing. Parquet ancien, double vitrage récent. Immeuble bien tenu avec gardien en loge.",
    tags: ['Lumineux', 'Traversant', 'Aligre'],
    features: ['Parquet', 'Double vitrage', 'Cave', 'Gardien'],
    dpe: 'D',
    ges: 'D',
    floor: 3,
    totalFloors: 6,
    orientation: 'Est-Ouest traversant',
    exteriorType: 'Pas d\'extérieur',
    heatingType: 'Collectif (gaz)',
    hotWaterType: 'Collectif (gaz)',
    yearBuilt: 1965,
    lotCount: 24,
    proceduresEnCours: false,
    monthlyCharges: 210,
    propertyTax: 980,
    composition: [
      { label: 'Séjour / salon', surface: 22 },
      { label: 'Cuisine ouverte', surface: 8 },
      { label: 'Chambre 1 + dressing', surface: 12 },
      { label: 'Chambre 2', surface: 10 },
      { label: 'Salle de bain', surface: 5 },
    ],
    irisZone: 'Quinze-Vingts – Aligre',
    irisDescription: 'Quartier en plein essor autour du marché d\'Aligre, mêlant bohème et mixité sociale à deux pas de la Bastille.',
    mapLat: 48.8505,
    mapLng: 2.3709,
    transports: ['M8 Ledru-Rollin', 'M1 Gare de Lyon', 'Bus 46'],
    nearbyPlaces: ['Marché d\'Aligre', 'Place de la Bastille', 'Port de Plaisance'],
    neighborhoodVibe: 'Vivant & mixte',
    marketAvgPricePerSqm: 9800,
    marketEvolution10y: '+35%',
    marketHighPrice: 12500,
    marketLowPrice: 7800,
    videoUrl: '/videos/bien-4.mp4',
    imageUrlFallback:
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=1400&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&h=600&fit=crop&q=80',
    ],
    chapters: [
      { label: 'Séjour',   fraction: 0    },
      { label: 'Cuisine',  fraction: 0.35 },
      { label: 'Chambres', fraction: 0.65 },
    ],
    likeCount: 0,
    shareCount: 0,
    promising: false,
  },
]
