/**
 * Shomee — shared TypeScript types.
 *
 * The `Property` interface below is the **view model** consumed by the feed
 * and detail UI. It is intentionally kept backward-compatible with existing
 * components and `lib/mockData.ts`; new fields aligned with the Prisma model
 * are all optional.
 *
 * Persistence-level entity types (User, Agent, Agency, BuyerProfile,
 * PropertyTag, VideoAnalysis, Document) and enums are generated by Prisma
 * and re-exported below as the single source of truth.
 */

import type {
  User,
  Agent,
  Agency,
  BuyerProfile,
  PropertyTag,
  VideoAnalysis,
  Document,
  Property as PrismaProperty,
  UserRole,
  AgencyPlan,
  MandatType,
  PropertyStatus,
  TagSource,
  VideoAnalysisStatus,
  DocumentType,
  PropertyBadge,
  DpeRating,
} from '@prisma/client'

export type {
  User,
  Agent,
  Agency,
  BuyerProfile,
  PropertyTag,
  VideoAnalysis,
  Document,
  PrismaProperty,
  UserRole,
  AgencyPlan,
  MandatType,
  PropertyStatus,
  TagSource,
  VideoAnalysisStatus,
  DocumentType,
  PropertyBadge,
  DpeRating,
}

export interface ChatMessage {
  id: string
  text: string
  from: 'user' | 'agent'
  timestamp: number  // Date.now()
  read: boolean
}

export interface Conversation {
  propertyId: string
  messages: ChatMessage[]
  lastSeenAt: number  // timestamp of last user view; agent msgs after this are "unread"
}

export interface Property {
  id: string
  // Matching engine — attached by /api/properties when buyerProfileId is set.
  // Score is in 0..1 (engine produces 0..100 → normalised in the route).
  matchScore?: number
  isExcluded?: boolean
  // Feed display
  arrondissement: string   // e.g. "PARIS 4e"
  subtitle: string         // e.g. "Appartement haussmannien"
  agentName: string
  agentAvatar?: string
  // Core data
  title: string
  price: number
  pricePerSqm?: number
  surface: number
  rooms: number
  bedrooms?: number
  location: string
  district: string
  description: string
  tags: string[]
  features?: string[]
  dpe: 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G'
  ges?: 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G'
  // Detail — physical
  floor?: number
  totalFloors?: number
  orientation?: string
  exteriorType?: string        // e.g. "Terrasse", "Balcon", "Jardin"
  heatingType?: string
  hotWaterType?: string
  yearBuilt?: number
  lotCount?: number
  proceduresEnCours?: boolean
  monthlyCharges?: number
  propertyTax?: number
  // Detail — composition
  composition?: Array<{ label: string; surface: number }>
  // Detail — localisation IRIS
  irisZone?: string            // micro-quartier IRIS sans adresse exacte
  irisDescription?: string
  irisPolygon?: [number, number][]
  mapLat?: number
  mapLng?: number
  transports?: string[]
  nearbyPlaces?: string[]
  neighborhoodVibe?: string
  mapTransports?: Array<{ name: string; line: string; lat: number; lng: number }>
  mapPois?: Array<{ name: string; lat: number; lng: number }>
  // Detail — marché
  marketAvgPricePerSqm?: number
  marketEvolution10y?: string  // e.g. "+27%"
  marketHighPrice?: number
  marketLowPrice?: number
  // Media
  videoUrl?: string
  matterportUrl?: string
  imageUrlFallback: string
  gallery: string[]
  chapters?: Array<{ label: string; fraction: number }>
  // Social
  likeCount?: number
  shareCount?: number
  promising?: boolean
  badges?: Array<'avant-premiere' | 'exclusivite'>

  // ─── Sprint fields (synced with Prisma Property) ────────────────────────
  mandatType?: 'EXCLUSIF' | 'SIMPLE' | 'COEXCLUSIF'
  avantPremiere?: boolean
  refInterneAgence?: string
  statut?: 'DRAFT' | 'PUBLISHED' | 'UNPUBLISHED' | 'ARCHIVED'
  completionRate?: number
  agencyId?: string
  createdByAgentId?: string
  collaborateurIds?: string[]

  // ─── Structured attributes (matching engine, PropertyStructuredAttributes) ─
  hasElevator?: boolean
  hasTerrace?: boolean
  terraceSurfaceM2?: number
  hasBalcony?: boolean
  balconySurfaceM2?: number
  hasGarden?: boolean
  gardenSurfaceM2?: number
  hasCellar?: boolean
  hasParking?: boolean
  hasConcierge?: boolean
  isGroundFloor?: boolean
  bedroomStreetSide?: boolean
  isQuietStreet?: boolean
  orientationStructured?: Array<'north' | 'south' | 'east' | 'west'>

  // ─── Semantic scores 0..1 (PropertySemanticScores) ──────────────────────
  luminosity?: number
  quietness?: number
  charm?: number
  spaciousness?: number
  livingQuality?: number
  outdoorUsability?: number

  // ─── LLM-filled marker (list of Property-side field keys) ───────────────
  llmFilledFields?: string[]

  // ─── Source markers (populated by the LLM importer) ─────────────────────
  locationSource?: string | null
  titleSource?: string | null
  priceSource?: string | null
  surfaceSource?: string | null
  roomsSource?: string | null
  bedroomsSource?: string | null
  descriptionSource?: string | null
  floorSource?: string | null
  yearBuiltSource?: string | null
  dpeSource?: string | null
  gesSource?: string | null
  mandatTypeSource?: string | null
  refInterneAgenceSource?: string | null
  monthlyChargesSource?: string | null
  propertyTaxSource?: string | null
  compositionSource?: string | null
}
